# Generated by Django 3.0.3 on 2020-05-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('no_of_adults', models.IntegerField()),
                ('no_of_childrens', models.IntegerField()),
                ('no_of_rooms', models.IntegerField()),
                ('want_for_meal', models.CharField(max_length=20)),
                ('mode_of_travel_car_flight', models.CharField(max_length=6)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('phone_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
