# Generated by Django 3.0.3 on 2020-05-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='bookings',
        ),
    ]
