# Generated by Django 3.0.3 on 2020-05-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0002_auto_20200522_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='username',
        ),
    ]
