# Generated by Django 3.0.3 on 2020-05-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_no', models.IntegerField()),
                ('destination_place', models.CharField(max_length=15)),
                ('no_of_days', models.IntegerField()),
                ('stay_charge', models.IntegerField()),
                ('food_charge', models.IntegerField()),
                ('car_charge', models.IntegerField()),
                ('airlines_charge', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=12)),
                ('lastname', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('profilePictures', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=12)),
                ('wish_to_stay', models.CharField(max_length=3)),
                ('no_of_days', models.IntegerField()),
                ('no_of_adults', models.IntegerField()),
                ('no_of_childrens', models.IntegerField()),
                ('no_of_rooms', models.IntegerField()),
                ('want_for_meal', models.CharField(max_length=3)),
                ('mode_of_travel_car_flight', models.CharField(max_length=6, null=True)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
